//
//  DataService.swift
//  Projectment
//
//  Created by Anar on 11.05.2020.
//  Copyright © 2020 Anar. All rights reserved.
//

import Realm

final class DataService {
  var tasks: [Task]? {
    [Task(id: "1",
          title: "Make login screen design",
          description: "Discuss with designers and development team all the details of the login screen and the date and complete the task",
          who: Teammate(id: "1",
                        name: "Kevin",
                        lastName: "Spacey",
                        job: .designer,
                        post: .middle),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .design,
          weight: .easy),
     Task(id: "2",
          title: "Configure GitHub",
          description: "Delegate to head of development team configuring github for remote control versions of the product",
          who: Teammate(id: "2",
                        name: "Abraham",
                        lastName: "Lincoln",
                        job: .developer,
                        post: .senior),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .development,
          weight: .easy),
     Task(id: "3",
          title: "Make login screen design",
          description: "Discuss with designers and development team all the details of the login screen and the date and complete the task",
          who: Teammate(id: "1",
                        name: "Kevin",
                        lastName: "Spacey",
                        job: .designer,
                        post: .middle),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .design,
          weight: .easy),
     Task(id: "4",
          title: "Configure GitHub",
          description: "Delegate to head of development team configuring github for remote control versions of the product",
          who: Teammate(id: "2",
                        name: "Abraham",
                        lastName: "Lincoln",
                        job: .developer,
                        post: .senior),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .development,
          weight: .easy),
     Task(id: "5",
          title: "Make login screen design",
          description: "Discuss with designers and development team all the details of the login screen and the date and complete the task",
          who: Teammate(id: "1",
                        name: "Kevin",
                        lastName: "Spacey",
                        job: .designer,
                        post: .middle),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .design,
          weight: .easy),
     Task(id: "6",
          title: "Configure GitHub",
          description: "Delegate to head of development team configuring github for remote control versions of the product",
          who: Teammate(id: "2",
                        name: "Abraham",
                        lastName: "Lincoln",
                        job: .developer,
                        post: .senior),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .development,
          weight: .easy),
     Task(id: "7",
          title: "Make login screen design",
          description: "Discuss with designers and development team all the details of the login screen and the date and complete the task",
          who: Teammate(id: "1",
                        name: "Kevin",
                        lastName: "Spacey",
                        job: .designer,
                        post: .middle),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .design,
          weight: .easy),
     Task(id: "8",
          title: "Configure GitHub",
          description: "Delegate to head of development team configuring github for remote control versions of the product",
          who: Teammate(id: "2",
                        name: "Abraham",
                        lastName: "Lincoln",
                        job: .developer,
                        post: .senior),
          created: Date(),
          expires: Date(timeIntervalSinceNow: .init(TimeService<Int>.secondsInDay)),
          state: .toDo,
          type: .development,
          weight: .easy)]
  }
}
